# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 04:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0003_auto_20170516_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='polarity',
        ),
    ]
