# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsApp', '0004_remove_article_polarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='address',
            field=models.CharField(default='', max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='result',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=140, null=True),
        ),
    ]
